name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: NPM install
      run: npm install
    - name: Test ${{ matrix.os }} node ${{ matrix.node-version }}
      run: npm run coverage --if-present
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: Test ${{ matrix.os }} node ${{ matrix.node-version }}
        parallel: true
    - name: Build bundle ${{ matrix.os }} node ${{ matrix.node-version }}
      run: npm run build --if-present
    - name: Test bundle ${{ matrix.os }} node ${{ matrix.node-version }}
      run: npm test
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true